// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using skyora1.DAL;

#nullable disable

namespace skyora1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519095754_updated2")]
    partial class updated2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("skyora1.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("skyora1.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedbackId");

                    b.ToTable("feedbacks");
                });

            modelBuilder.Entity("skyora1.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableBusinessSeats")
                        .HasColumnType("int");

                    b.Property<int>("AvailableEconomySeats")
                        .HasColumnType("int");

                    b.Property<decimal>("BusinessPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EconomyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FlightNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBusinessSeats")
                        .HasColumnType("int");

                    b.Property<int>("TotalEconomySeats")
                        .HasColumnType("int");

                    b.HasKey("FlightId");

                    b.ToTable("flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            ArrivalTime = new DateTime(2026, 5, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableBusinessSeats = 32,
                            AvailableEconomySeats = 150,
                            BusinessPrice = 15000m,
                            DepartureTime = new DateTime(2026, 5, 13, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Delhi",
                            EconomyPrice = 8000m,
                            FlightNo = "SK101",
                            Source = "Mumbai",
                            TotalBusinessSeats = 32,
                            TotalEconomySeats = 150
                        },
                        new
                        {
                            FlightId = 2,
                            ArrivalTime = new DateTime(2026, 5, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableBusinessSeats = 32,
                            AvailableEconomySeats = 150,
                            BusinessPrice = 14000m,
                            DepartureTime = new DateTime(2026, 5, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Bengaluru",
                            EconomyPrice = 7500m,
                            FlightNo = "SK102",
                            Source = "Delhi",
                            TotalBusinessSeats = 32,
                            TotalEconomySeats = 150
                        },
                        new
                        {
                            FlightId = 3,
                            ArrivalTime = new DateTime(2026, 5, 13, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableBusinessSeats = 32,
                            AvailableEconomySeats = 150,
                            BusinessPrice = 10000m,
                            DepartureTime = new DateTime(2026, 5, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Chennai",
                            EconomyPrice = 5500m,
                            FlightNo = "SK103",
                            Source = "Bengaluru",
                            TotalBusinessSeats = 32,
                            TotalEconomySeats = 150
                        },
                        new
                        {
                            FlightId = 4,
                            ArrivalTime = new DateTime(2026, 5, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableBusinessSeats = 32,
                            AvailableEconomySeats = 150,
                            BusinessPrice = 6000m,
                            DepartureTime = new DateTime(2026, 5, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Pune",
                            EconomyPrice = 3000m,
                            FlightNo = "SK104",
                            Source = "Mumbai",
                            TotalBusinessSeats = 32,
                            TotalEconomySeats = 150
                        },
                        new
                        {
                            FlightId = 5,
                            ArrivalTime = new DateTime(2026, 5, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableBusinessSeats = 32,
                            AvailableEconomySeats = 150,
                            BusinessPrice = 5000m,
                            DepartureTime = new DateTime(2026, 5, 13, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Jaipur",
                            EconomyPrice = 2500m,
                            FlightNo = "SK105",
                            Source = "Delhi",
                            TotalBusinessSeats = 32,
                            TotalEconomySeats = 150
                        },
                        new
                        {
                            FlightId = 6,
                            ArrivalTime = new DateTime(2026, 5, 13, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableBusinessSeats = 32,
                            AvailableEconomySeats = 150,
                            BusinessPrice = 12000m,
                            DepartureTime = new DateTime(2026, 5, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Delhi",
                            EconomyPrice = 6500m,
                            FlightNo = "SK106",
                            Source = "Kolkata",
                            TotalBusinessSeats = 32,
                            TotalEconomySeats = 150
                        },
                        new
                        {
                            FlightId = 7,
                            ArrivalTime = new DateTime(2026, 5, 13, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableBusinessSeats = 32,
                            AvailableEconomySeats = 150,
                            BusinessPrice = 9000m,
                            DepartureTime = new DateTime(2026, 5, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Bengaluru",
                            EconomyPrice = 4500m,
                            FlightNo = "SK107",
                            Source = "Hyderabad",
                            TotalBusinessSeats = 32,
                            TotalEconomySeats = 150
                        },
                        new
                        {
                            FlightId = 8,
                            ArrivalTime = new DateTime(2026, 5, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableBusinessSeats = 32,
                            AvailableEconomySeats = 150,
                            BusinessPrice = 8000m,
                            DepartureTime = new DateTime(2026, 5, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Ahmedabad",
                            EconomyPrice = 4000m,
                            FlightNo = "SK108",
                            Source = "Mumbai",
                            TotalBusinessSeats = 32,
                            TotalEconomySeats = 150
                        },
                        new
                        {
                            FlightId = 9,
                            ArrivalTime = new DateTime(2026, 5, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableBusinessSeats = 32,
                            AvailableEconomySeats = 150,
                            BusinessPrice = 9500m,
                            DepartureTime = new DateTime(2026, 5, 13, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Bengaluru",
                            EconomyPrice = 5000m,
                            FlightNo = "SK109",
                            Source = "Kochi",
                            TotalBusinessSeats = 32,
                            TotalEconomySeats = 150
                        },
                        new
                        {
                            FlightId = 10,
                            ArrivalTime = new DateTime(2026, 5, 13, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableBusinessSeats = 32,
                            AvailableEconomySeats = 150,
                            BusinessPrice = 7000m,
                            DepartureTime = new DateTime(2026, 5, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Delhi",
                            EconomyPrice = 3500m,
                            FlightNo = "SK110",
                            Source = "Lucknow",
                            TotalBusinessSeats = 32,
                            TotalEconomySeats = 150
                        });
                });

            modelBuilder.Entity("skyora1.Models.Messages", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("skyora1.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PassengerId");

                    b.HasIndex("BookingId");

                    b.ToTable("passengers");
                });

            modelBuilder.Entity("skyora1.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("skyora1.Models.Booking", b =>
                {
                    b.HasOne("skyora1.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("skyora1.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("skyora1.Models.Passenger", b =>
                {
                    b.HasOne("skyora1.Models.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("skyora1.Models.Booking", b =>
                {
                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("skyora1.Models.Flight", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("skyora1.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
